name: final_projects
description: "Key Of Sucess"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_spinkit: ^5.2.1
  # web services
  http: ^1.2.2
  # database
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  # operation
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.6
  either_dart: ^1.0.0
  connectivity_plus: ^6.1.0
  #styles
  flutter_native_splash: ^2.4.3
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  #widgets
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_svg: ^2.0.15
  lottie: ^3.1.3
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  pull_to_refresh: ^2.0.0
  video_player: ^2.9.2
  #additinal
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  path: ^1.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/videos/